In [19]:
import numpy as np

f=np.array([12,23,45,60,75])

c=np.empty(len(f))

for i in range(len(f)):
    j=(f[i]-32)*(5/9)
    c[i]=j
    print(f'Celsius value of {f[i]} is {j}')


Celsius value of 12 is -11.11111111111111
Celsius value of 23 is -5.0
Celsius value of 45 is 7.222222222222222
Celsius value of 60 is 15.555555555555557
Celsius value of 75 is 23.88888888888889


In [33]:
x=np.random.randint(0,1001,size=1000)
print(f"random array is: \n{x}")
avg=np.average(x)
print(f"average of the array: {avg}")
var=np.var(x)
print(f"variance of the array: {var}")
sd=np.std(x)
print(f"standard deviation of the array: {sd}")

random array is: 
[ 310  355  339   14  466  898  671  883  314  983  483  210  166  588
  703   15   18  979  508  107  945  962  383  681  852  986  201  863
  304  588  306  696  887  552  455  221  520  655   77  969  776  769
  414  680  983  962  285  748  312    8  822  676  130  289  517  847
   68  854  939  179  829  521  259  784  803  332  480  594    9  431
  807   32  407  550  261  262  153  680  302  554   42  950  761  929
  443   48  274  185  970  802  954  531  175  931  972  164  640  549
  388   60  435  683  292  513  218  450   91   10  440  179   91    1
  464  884  833  492  778  415  929  157  524  825  553  751  339  605
  429   73  773  581  507  753  474  816  184   36  510   69  870  127
  728  906   92  452  605  199  770  497  506  959  739  148   70  566
  644  105  523  870  234  555  690  115  126   21  249  165   81   84
  506  491  218  150  253   96  794  287  409  388  661  173  530  776
  109  244  430  320  763  355  344  522  268  882  154  23

In [35]:
a=np.array([30,60,90,180])
np.radians(a)

array([0.52359878, 1.04719755, 1.57079633, 3.14159265])

In [36]:
b=np.array([77,31,10,19,17,69,24])
dif=np.diff(b)
dif

array([-46, -21,   9,  -2,  52, -45])

In [73]:
comp=np.array([ 5-6j, 3+4j, 7+3j,1+2j, 3+2j])
print(f"unsorted array: {comp}")
sor=np.sort_complex(comp)
print(f"sorted array: {sor}")

unsorted array: [5.-6.j 3.+4.j 7.+3.j 1.+2.j 3.+2.j]
sorted array: [1.+2.j 3.+2.j 3.+4.j 5.-6.j 7.+3.j]


In [ ]:
new=np.random.randint(0,10,10)
print(new)
gt=np.where(new>4)
for i in gt:
    print(new[i])

[1 2 3 0 5 1 0 9 2 8]
[5 9 8]


In [ ]:
d=np.random.randint(0,10,5)
item=int(input("Enter the element to search: "))
index=np.where(d==item)
print(d)
if index[0].size==0:
    print("Element is not in the array")
else:
    print(f"Element is found at the index: {index[0]}")

[5 9 6 6 0]
Element is found at the index: [2 3]


In [76]:
z=np.random.randint(0,10,10)
done=np.savetxt("newfile.txt",z)
if done:
    print("success")

In [63]:
ev=np.arange(30,61,2)
print(ev)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [72]:
dim1,dim2=map(int, input("Enter the dimensions of the array: ").split())
y=np.random.randint(0,10,size=(dim1,dim2))
print("array: ",y)
print("sum is: ", np.sum(y))
print("sum of columns: ",np.sum(y, axis=0))
print("sum of rows: ", np.sum(y, axis=1))

array:  [[3 7 4 9]
 [3 5 5 3]
 [1 5 2 7]]
sum is:  54
sum of columns:  [ 7 17 11 19]
sum of rows:  [23 16 15]
