We are importing numpy

In [1]:
import numpy as np



 tuple to numpy array

In [1]:
a=(1,2,3,4)
print(type(a))

b=np.array(a)
print(b)
type(b)

<class 'tuple'>


NameError: name 'np' is not defined

Arange

In [ ]:
c=np.arange(10)
print(c)

c=np.arange(2,101,2)
print(c)

d=np.arange(1,100,2)
print(d)

print(d[4:10])

print(d[:5])

print(d[40:])

print(d[-4:-1])

print(d[3])




[0 1 2 3 4 5 6 7 8 9]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[ 9 11 13 15 17 19]
[1 3 5 7 9]
[81 83 85 87 89 91 93 95 97 99]
[93 95 97]
7
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
z= [ 1  2  3  4 22  6  7  8  9]
y= [ 1  2  3  4 22  6  7  8  9]
z= [ 1  2  3  4 32  6  7  8  9]
x= [ 1  2  3  4 22  6  7  8  9]


Zeros

In [18]:
e=np.zeros(10,int)
print(e)
e=np.zeros(10)
print(e)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ones

In [19]:
f=np.ones(10,int)
print(f)
f=np.ones((3,3),int)
f

[1 1 1 1 1 1 1 1 1 1]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Matrix

In [22]:
g=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(g)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


Eye and Identity matrix

In [35]:
h=np.eye(3,dtype=int)
print(h)
h=np.identity(4,dtype=int)
print(h)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Copy()

In [ ]:
z=np.arange(1,10)
print(z)

y=z
print(y)
z[4]=22
print("z=",z)
print("y=",y)

x=z.copy()
z[4]=32
print("z=",z)
print("x=",x)

Concat

In [59]:
i=np.array([[1,2],[3,4]])
j=np.array([[5,6],[7,8]])
k=np.concatenate((i,j),axis=1)
print(k)

[[1 2 5 6]
 [3 4 7 8]]


In [65]:
l=np.array([1,2,3,4,5,6,7,8])
m=np.where(l==6)

if 0 in m[0]:
    print("number not found")
else:
    print("number found at ",*m[0])

print(m[0])

#without brackets : 
print("element is fount at ",*m[0])



number found at  5
[5]
element is fount at  5
